### ISSUE TITLE
Upgrade to bevy 0.10

### ISSUE THREAD

**Issue by raffaeleragni** [jakobhellermann/bevy_ecs_dynamic#3]
Hi, is there any plan to upgrade this crate to work with bevy 0.10?

**Comment by jakobhellermann** [comment]
I'm not currently using this crate so it hasn't been a priority so far, but I'll update it if I find some time to work on it :+1:

**Comment by raffaeleragni** [comment]
Anything I can do to help?
I have a fork. Most of the code seems to deal with internal stuff tho so I am not sure where I could touch anything.
